
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "\x1c\xa1Bx\n\x08\xc2\xde\xc1\xa9q\x04\xe3\x84A'"
    
_lr_action_items = {'AND':([3,5,8,9,10,11,12,13,14,],[6,6,-6,-4,-5,-7,-3,6,6,]),'TERM':([0,2,6,7,],[1,1,1,1,]),'RPAREN':([5,8,9,10,11,12,13,14,],[12,-6,-4,-5,-7,-3,-1,-2,]),'STRING':([4,],[8,]),'EQUALS':([1,],[4,]),'NUMBER':([4,],[10,]),'BOOL':([4,],[11,]),'LPAREN':([0,2,6,7,],[2,2,2,2,]),'OR':([3,5,8,9,10,11,12,13,14,],[7,7,-6,-4,-5,-7,-3,7,7,]),'$end':([3,8,9,10,11,12,13,14,],[0,-6,-4,-5,-7,-3,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'identifier':([0,2,6,7,],[3,5,13,14,]),'value':([4,],[9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> identifier","S'",1,None,None,None),
  ('identifier -> identifier AND identifier','identifier',3,'p_identifier_and','../../AXUI/parsing/identifier_parsing.py',55),
  ('identifier -> identifier OR identifier','identifier',3,'p_identifier_or','../../AXUI/parsing/identifier_parsing.py',59),
  ('identifier -> LPAREN identifier RPAREN','identifier',3,'p_identifier_paren','../../AXUI/parsing/identifier_parsing.py',63),
  ('identifier -> TERM EQUALS value','identifier',3,'p_identifier','../../AXUI/parsing/identifier_parsing.py',67),
  ('value -> NUMBER','value',1,'p_value_number','../../AXUI/parsing/identifier_parsing.py',71),
  ('value -> STRING','value',1,'p_value_string','../../AXUI/parsing/identifier_parsing.py',75),
  ('value -> BOOL','value',1,'p_value_bool','../../AXUI/parsing/identifier_parsing.py',79),
]
